# This file contains all available configuration options
# with their default values (in comments).

# Options for analysis running.
run:
  tests: false

linters:
  enable-all: true
  disable:
    - varnamelen
    - exhaustivestruct
    - gomnd
    - cyclop
    - maligned
    - funlen
    - gocyclo
